conf .defaults
jail pi
mode casual
# Let pi access its own config.
dir! .pi
# Allow access to the shared cache instead of writing out a separate, parallel
# cache.
dir .cache
# Allow access to nvim plugins (auto-installed).
dir .local/share/nvim
# Allow access to shared sockets (mostly: wayland clipboard).
dir /run/user/1000
# Read the pi install location (installed via bun).
rdir .bun
# Access project dirs.
dir p
dir 3p
dir w
dir x
command pi "$@"
