#!/usr/bin/env ruby

USAGE =<<EOS
Usage:

  $ git sync <newbase> [branch]

"git sync master topic" is shorthand for the following:

  $ git rebase master topic
  $ git checkout master
  $ git merge topic

EOS

if ARGV.empty?
  abort USAGE
end

new_base = ARGV[0]
branch_output = `git branch --no-color`.split("\n").select { |name| name =~ /^\*/ }
raise "Not on a valid branch" unless branch_output.size == 1
current_branch = branch_output[0].gsub(/^\*\s+/, "")
target_branch = ARGV.size > 1 ? ARGV[1] : current_branch

def run_and_check(command)
  abort unless system command
end

run_and_check "git rebase #{new_base} #{target_branch}"
run_and_check "git checkout #{new_base}"
run_and_check "git merge #{target_branch}"
run_and_check "git checkout #{current_branch}"
