#!/bin/bash
set -eu -o pipefail

# TODO: I'm setting --lines to a value 1 more than needed due to this bug:
# https://codeberg.org/dnkl/fuzzel/issues/234.
# In addition, https://codeberg.org/dnkl/fuzzel/issues/144 tracks the feature
# whereby I could use --minimal-lines rather than specifying a particular number
# of --lines at all.

function prompt() {
  echo -e ' Lock\n Suspend\n Exit Sway\n Reboot\n Power off' |
    fuzzel \
      --dmenu \
      --index \
      --lines 6 \
      --width 15
}

function confirm() {
  echo -e ' No\n Yes' |
    fuzzel \
      --dmenu \
      --index \
      --prompt 'Are you sure? ' \
      --lines 3 \
      --width 15
}

function with_prompt() {
  if [[ "$(confirm)" == 1 ]]; then
    exec "$@"
  else
    exit 0
  fi
}

case "$(prompt)" in
  0)
    exec swaylock
    ;;
  1)
    if [[ "$(sudo dmidecode --string chassis-type | tr A-Z a-z)" == 'desktop' ]]; then
      with_prompt systemctl suspend
    else
      with_prompt systemctl suspend-then-hibernate
    fi
    ;;
  2)
    with_prompt swaymsg exit
    ;;
  3)
    with_prompt systemctl reboot
    ;;
  4)
    with_prompt systemctl poweroff
    ;;
esac
